### ISSUE TITLE
Our new Events api should weed old events out of the delivery. At the moment, a September event is showing on the homepage.

### ISSUE THREAD

**Issue by michaelschofield** [fontana-regional-library/feathers-design-system#28]
## Feature or problem
This should be addressed from the back end in Big Kahuna.

![weed-old-events-from-new-events-api.PNG](https://images.zenhubusercontent.com/5907891d51aa2c30577cf4d5/0921aab5-1e23-4d32-ac31-f25f28a8f659)

**Comment by awestlib** [comment]
@michaelschofield The events API should be doing this -- that event is misconfigured in the drupal Staff portal (it's scheduled for ongoing with a startdate of Sept. 2018 and end date sometime in 2020, rather than as a recurring, multi-occurrence event.)
